version: '2'
services:
  web:
    build: .
    volumes:
      - .:/room-scheduler
    ports:
      - "4000:4000"
    env_file: .env
    environment:
      HOST: 0.0.0.0
      PG_HOST: postgres

    links:
      - postgres

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres